### ISSUE TITLE
ZipFile invalid LOC header

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#152]
Hi there!

Starting to get random 500 errors in keycloak backend caused by ZIP (jar?) file with [such stack trace](https://gist.github.com/hookenful/e358ed702a8866f556c398a108df5333). 
We are copying our build .jar output to src/keycloak/theme which is copying by gitlab ci to` .keycloakconf/theme` folder on node and being picked-up by keycloak engine in providers folder, e.g in our docker compose:

```
volumes:
      - ./.keycloakconf/theme/:/opt/keycloak/providers/:rw
```

It keeps occur more frequent, so this is will be disaster on production. Any thoughts on these?

**Comment by hookenful** [comment]
Can you help with determining minimal setup on linux to get theme's .jar file? I mean, maybe some steps like install maven, etc ?

**Comment by garronej** [comment]
Hi @hookenful,  
Are you sure the problem is related to keycloakify? Have you tried with another theme?

**Comment by garronej** [comment]
> 
Can you help with determining minimal setup on linux to get theme's .jar file? I mean, maybe some steps like install maven, etc ?  

If you just need the .jar you can download the one of the demo app:  
https://github.com/garronej/keycloakify-demo-app/releases  
https://github.com/garronej/keycloakify-demo-app/releases/download/v0.4.4/standalone-keycloak-theme.jar

**Comment by hookenful** [comment]
Hey!

I dunno is this still relevant, I have written a stage for gitlab ci to build theme. `REACT_APP_STAGE ` is our trigger env to let our app build only in keycloak mode, because we have it in same package with main app.

```
build-keycloak-theme:
  stage: build-theme
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /release/
    - if: $CI_COMMIT_BRANCH == "devserver"
  before_script:
    - apk add --update npm yarn curl maven
    - unset CI
    - export REACT_APP_STAGE=keycloak
    - cd src/web
  script:
    - yarn install --immutable
    - yarn build
    - npx build-keycloak-theme
    - mkdir $CI_PROJECT_DIR/src/keycloak/theme
    - cp -r $(pwd)/build_keycloak/target/*.jar $CI_PROJECT_DIR/src/keycloak/theme
    - ls -la $CI_PROJECT_DIR/src/keycloak/theme
  artifacts:
    paths:
      - src/keycloak/theme/*.jar
```
