### ISSUE TITLE
MVN command not found on Github self-hosted runner

### ISSUE THREAD

**Issue by shubhamdeodia** [InseeFrLab/keycloakify#59]
I have install maven on our company's self hosted runner and verified from workflow the `mvn -version` is showing that maven is installed.

still when I run the `build-keycloak-theme` it gives me error

```
/bin/sh: mvn: command not found
node:child_process:903
    throw err;
    ^

Error: Command failed: mvn package
/bin/sh: mvn: command not found

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
```

any idea how I can resolve this issue ?

**Comment by garronej** [comment]
Hi,  
It must not be in the `PATH` when the script run. Are you sure the script is not run by a different user that hase a different `PATH`.

**Comment by shubhamdeodia** [comment]
This is my workflow file, runner already has mvn install, what you are saying is that I should remove the PATH env ?

```
name: ci
on:
  push:
    branches:
      - test

jobs:
  build:
    name: build
    runs-on: 'custom-runner'
    steps:
      - run: sudo chown -R $USER:$USER ${{ github.workspace }}

      - uses: actions/checkout@v2
      - name: show maven version
        run: |
          export M2_HOME=/usr/local/apache-maven
          export M2=$M2_HOME/bin 
          export PATH=$M2:$PATH
          mvn -version

      # Setup NodeJS and NPM
      - name: 'Setup Nodejs'
        uses: actions/setup-node@v2.3.0
        with:
          node-version: '16.x'

      - name: install dependencies
        run: npm install

      - run: npm run keycloak-ci
      - uses: actions/upload-artifact@v2
        with:
          name: keycloak_theme
          path: build_keycloak/target/*keycloak-theme*.jar

```
